Rails/Projekte/books/config/routes.rb
Rails.application.routes.draw do

	root 'books#index'
  resources :books do
  	  resources :likes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails/Projekte/books/app/models/book.rb
class Book < ApplicationRecord
	has_many :likes, :dependent => :destroy
end

Rails/Projekte/books/app/models/like.rb
class Like < ApplicationRecord
	belongs_to :book
	/HOW_HEARD_OPTIONS = [
  			1,
  			2,
  			3,
  			4,
  			5
  	]
		validates :quality, inclusion: { in: HOW_HEARD_OPTIONS }
	/
		validates :quality, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 } 
end

Rails/Projekte/books/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:author, :title, :description, :published_on)
    end
end

Rails/Projekte/books/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]
  before_action :set_book
  # GET /likes
  # GET /likes.json
  def index
    @likes = @book.likes
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = @book.likes.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = @book.likes.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to book_likes_path(@book.id, @like.id), notice: 'Like was successfully created.' }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to book_likes_path(@book.id, @like.id), notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to book_likes_url(@book.id), notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end
    def set_book
      @book = Book.find(params[:book_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      params.require(:like).permit(:quality, :book_id)
    end
end

Rails/Projekte/books/app/helpers/books_helper.rb
module BooksHelper
	def mittel(book)
		if book.likes.count > 0 
			i=0
			book.likes.each do |f|
				i=i+f.quality
			end
			e=i/book.likes.count
		else
			0			
		end
	end
end

Rails/Projekte/books/app/views/layouts/_top_bar.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Site Title</li>
      <li>
        <a href="#">One</a>
        <ul class="menu vertical">
          <li><a href="#">One</a></li>
          <li><a href="#">Two</a></li>
          <li><a href="#">Three</a></li>
        </ul>
      </li>
      <li><a href="#">Two</a></li>
      <%= link_to "Index", root_path() %>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Search"></li>
      <li><button type="button" class="button">Search</button></li>
    </ul>
  </div>
</div>

Rails/Projekte/books/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/top_bar' %>
    <%= yield %>

  </body>
</html>

Rails/Projekte/books/app/views/likes/_form.html.erb
<%= form_for([@book,@like]) do |f| %>
  <% if like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quality %>
    <%= f.number_field :quality %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/Projekte/books/app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Show', book_like_path(@book.id, @like.id) %> |
<%= link_to 'Back', book_like_path(@book.id) %>

Rails/Projekte/books/app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Likes</h1>

<table>
  <thead>
    <tr>
      <th>Quality</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.quality %></td>
        <td><%= link_to 'Show', book_like_path(@book.id, like.id) %></td>
        <td><%= link_to 'Edit', edit_book_like_path(@book.id, like.id) %></td>
        <td><%= link_to 'Destroy', book_like_path(@book.id, like.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_book_like_path(@book.id) %>

Rails/Projekte/books/app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Back', book_likes_path(@book.id) %>

Rails/Projekte/books/app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quality:</strong>
  <%= @like.quality %>
</p>

<%= link_to 'Edit', edit_book_like_path(@book.id, @like.id) %> |
<%= link_to 'Back', book_likes_path(@book.id) %>